language: python

python:
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch

before_install:

# command to install dependencies
install:
  - pip install .

# command to run tests
script:
  - python -m tests.unittests_estimators
  - python -m tests.unittests_evaluations
  - python -m tests.unittests_simulations
  - python -m tests.unittests_utils

notifications:
  email:
    recipients:
      - jonas.rothfuss@gmail.com
    on_success: never
    on_failure: never