language: python

python:
  - "3.5"
  - "3.6"
  - "3.6-dev"  # 3.6 development branch

before_install:

# command to install dependencies
install:
  - pip install .

# command to run tests
script:
  - python tests/unittests_estimators.py
  - python tests/unittests_evaluations.py
  - python tests/unittests_simulations.py
  - python tests/unittests_utils.py

notifications:
  email:
    recipients:
      - jonas.rothfuss@gmail.com
      - fabioferreira@mailbox.org
    on_success: never
    on_failure: never
